<?php
/**
 * Implementation of hook_node_view
 */
function serenitysites_node_view($node, $view_mode, $langcode) {
  if ($node->type == 'directions' && $view_mode == 'full') {

    $locationmap_path = drupal_get_path('module', 'locationmap');
    drupal_add_js('http://maps.google.com/maps/api/js?v=3&sensor=false',  array('type' => 'external', 'weight' => 5));
    drupal_add_js($locationmap_path . '/locationmap.js', array('type' => 'file', 'weight' => 6, 'scope' => 'footer'));

    
    $address = serenitysites_get_address($node->field_directions_address[LANGUAGE_NONE][0]['value']);
    if (!empty($address)) {
      $address = implode(' ', $address);
      $coordinates = locationmap_geocode_for_address($address);
 
      $locationmap_settings = array(
        'address' => $address,
        'info' => $address,
        'lat' => $coordinates[0],
        'lng' => $coordinates[1],
        'zoom' => variable_get('locationmap_zoom', 14),
        'type' => variable_get('locationmap_type', 'google.maps.MapTypeId.ROADMAP'),
      );
      drupal_add_js(array('locationmap' => $locationmap_settings), 'setting');
        
      $node->content['map'] = array('#type' => 'markup', '#markup' => theme('locationmap_map'), '#weight' => 10);
    }
  }
}

/**
 * Get address from the fieldcollection id
 */
function serenitysites_get_address($field_collection_id) {
  $address = array();
  $entity = entity_load('field_collection_item', array($field_collection_id));
  if (!empty($entity)) {
    $entity = array_pop($entity);
    $address = array(
      'address' =>$entity->field_directions_street_address[LANGUAGE_NONE][0]['value'],
      'city' => $entity->field_directions_city[LANGUAGE_NONE][0]['value'],
      'state' => $entity->field_directions_state[LANGUAGE_NONE][0]['value'],
      'zip' => $entity->field_directions_zip[LANGUAGE_NONE][0]['value']
    );
  }
  return $address;
}

/**
 * Create new language, used to distinguish domains
 */
function serenitysites_create_language(){
  $langcode = 'u-1';
  $name = 'mike.dorrell';
  $direction = 0;
  $domain = '';
  $prefix = $name;
  locale_add_language($langcode, $name, $name, $direction, $domain, $prefix);
    
}
