<?php
/**
 * Implement hook_block_info()
 */
function serenitysites_block_info() {
  $blocks = array();
  $blocks['sites_main_menu'] = array(
    'info' => t('Sites Main Menu')
  );
  return $blocks;
}

/**
 * Implement hook_block_view()
 */
function serenitysites_block_view($delta='') {
  $block = array();
  switch ($delta) {
    case 'sites_main_menu':
      $block['content'] = serenitysites_main_main_block_contents();
      break;
  }
  return $block;
}

/**
 * Display correct menu for "language"
 */
function serenitysites_main_main_block_contents() {
  global $language;

  $menu_name = 'main-menu';
  if ($language->language != 'en') {
    $menu_name = 'menu-main-menu-' . str_replace('.', '-', $language->language);
  }
  
  $main_menu_tree = menu_tree($menu_name); 
	$content = '<div id="main-menu">' . drupal_render($main_menu_tree) . '</div>';
  return $content;
}

/**
 * Implementation of hook_node_view
 */
function serenitysites_node_view($node, $view_mode, $langcode) {
  if ($node->type == 'directions' && $view_mode == 'full') {

    $locationmap_path = drupal_get_path('module', 'locationmap');
    drupal_add_js('http://maps.google.com/maps/api/js?v=3&sensor=false',  array('type' => 'external', 'weight' => 5));
    drupal_add_js($locationmap_path . '/locationmap.js', array('type' => 'file', 'weight' => 6, 'scope' => 'footer'));

    
    $address = serenitysites_get_address($node->field_directions_address[LANGUAGE_NONE][0]['value']);
    if (!empty($address)) {
      $address = implode(' ', $address);
      $coordinates = locationmap_geocode_for_address($address);
 
      $locationmap_settings = array(
        'address' => $address,
        'info' => $address,
        'lat' => $coordinates[0],
        'lng' => $coordinates[1],
        'zoom' => variable_get('locationmap_zoom', 14),
        'type' => variable_get('locationmap_type', 'google.maps.MapTypeId.ROADMAP'),
      );
      drupal_add_js(array('locationmap' => $locationmap_settings), 'setting');
        
      $node->content['map'] = array('#type' => 'markup', '#markup' => theme('locationmap_map'), '#weight' => 10);
    }
  }
}

/**
 * Get address from the fieldcollection id
 */
function serenitysites_get_address($field_collection_id) {
  $address = array();
  $entity = entity_load('field_collection_item', array($field_collection_id));
  if (!empty($entity)) {
    $entity = array_pop($entity);
    $address = array(
      'address' =>$entity->field_directions_street_address[LANGUAGE_NONE][0]['value'],
      'city' => $entity->field_directions_city[LANGUAGE_NONE][0]['value'],
      'state' => $entity->field_directions_state[LANGUAGE_NONE][0]['value'],
      'zip' => $entity->field_directions_zip[LANGUAGE_NONE][0]['value']
    );
  }
  return $address;
}

/**
 * Create new language, used to distinguish domains
 */
function serenitysites_create_language(){
  $langcode = 'u-1';
  $name = 'mike.dorrell';
  $direction = 0;
  $domain = '';
  $prefix = $name;
  locale_add_language($langcode, $name, $name, $direction, $domain, $prefix);
    
}

/**
 * Create initial nodes for new user site
 */
function serenitysites_setup_site() {
  $uid = 1;
  serenitysites_setup_node('about_us', 'About Us', $uid, 'about-us');
  serenitysites_setup_node('directions', 'Directions', $uid, 'directions');
  serenitysites_setup_node('page', 'Pre-Arrangements', $uid, 'pre-arrangements');
}

/**
 * Create simple node
 */
function serenitysites_setup_node($type, $title, $uid, $path) {
  $node = new stdClass();
  $node->type = $type;
  node_object_prepare($node);

  $node->title = $title;
  $node->language = 'u-' . $uid;
  $node->path = array('alias' => $path);
  $node->uid = $uid;
  node_save($node);
}

/**
 * Initialize a menu for a new site
 */
function serenitysites_setup_menu($uid, $language) {
  $menu_name = 'menu-main-menu-u-' . $uid;
  $menu = array(
    'menu_name' => $menu_name,
    'title' => 'Main Menu (u-' . $uid . ')',
    'language' => $language,
    'i18n_mode' => 2,
  );
  menu_save($menu);

  $link = array(
    'link_title' => t('Home'),
    'link_path' => drupal_get_normal_path('<front>', $language),
    'menu_name' => $menu_name,
    'weight' => 0
  );
  menu_link_save($link);
  
  $link = array(
    'link_title' => t('About Us'),
    'link_path' => drupal_get_normal_path('about-us', $language),
    'menu_name' => $menu_name,
    'weight' => 1
  );
  menu_link_save($link);
  
  $link = array(
    'link_title' => t('Obituaries'),
    'link_path' => drupal_get_normal_path('obituaries', $language),
    'menu_name' => $menu_name,
    'weight' => 2
  );
  menu_link_save($link);
  
  $link = array(
    'link_title' => t('Directions'),
    'link_path' => drupal_get_normal_path('directions', $language),
    'menu_name' => $menu_name,
    'weight' => 3
  );
  menu_link_save($link);
  
  $link = array(
    'link_title' => t('Pre-Arrangements'),
    'link_path' => drupal_get_normal_path('pre-arrangements', $language),
    'menu_name' => $menu_name,
    'weight' => 4
  );
  menu_link_save($link);
  
  $link = array(
    'link_title' => t('Contact Us'),
    'link_path' => drupal_get_normal_path('contact-us', $language),
    'menu_name' => $menu_name,
    'weight' => 5
  );
  menu_link_save($link);
    
  menu_cache_clear_all();
}

