<?php
/**
 * implementation of hook_permission
 */
function serenity_dashboard_permission() {
  return array(
    'administer dashboard' => array(
      'title' => t('Administer Serenity Dashboard'), 
      'description' => t('Manage pages on the site'),
    ),
  );
}

/**
 * implementation of hook_menu
 */
function serenity_dashboard_menu() {
	$items['user/dashboard'] = array(
    'title' => 'Dashboard',
    'description' => 'Site Management',
    'page callback' => 'serenity_dashboard_page',
    'access arguments' => array('administer dashboard'),
    'file' => 'serenity_dashboard.menu.inc',
  );
  return $items;
}

/**
 * Implementation of hook_form_alter
 */
function serenity_dashboard_form_alter(&$form, &$form_state, $form_id) {
	if ($form_id == 'menu_overview_form') {
    $arg = arg();
    if ($arg[0] == 'user' && $arg[1] == 'dashboard') {
      //$form['#submit'][] = 'serenity_dashboard_form_submit';
  		foreach (element_children($form) as $id) {
        // only look at menu items
  			if (!empty($form[$id]['mlid'])) {
          $link_path = $form[$id]['#item']['link_path'];
          if (substr($link_path, 0, 5) == 'node/') {
            $form[$id]['operations']['edit']['#href'] = $link_path . '/edit';
          }
          elseif ($link_path == '<front>') {
            $front_path = drupal_lookup_path('source', 'home');
            $form[$id]['operations']['edit']['#href'] = $front_path . '/edit';
          }
          else {
            $form[$id]['operations']['edit']['#type'] = 'markup';
            $form[$id]['operations']['edit']['#value'] = '';
          }
          $form[$id]['operations']['edit']['#options'] = array('query' => array('destination' => 'user/dashboard'));

          $form[$id]['operations']['delete'] = array(
            '#type' => 'link',
            '#title' => 'Add page',
            '#href' => 'node/add/page',
            '#options' => array('query' => array('destination' => 'user/dashboard', 'mlid' => $form[$id]['mlid']['#value'])),
          );
  			}
  		}
    }
	}
}

/**
 * hook_submit for dashboard form
 */
// function serenity_dashboard_form_submit($form, &$form_state) {
//   dsm($form_state);
// }

function serenity_dashboard_init() {
  global $language;

  $path = current_path();
  // check if current menu is active
  $query = db_select('menu_links', 'ml');
  $query->condition('ml.link_path', $path)
    ->condition('ml.menu_name', 'menu-main-menu-' . $language->language)
    ->fields('ml', array('mlid', 'hidden'));
  $result = $query->execute()->fetchAssoc();
  if ($result['hidden']) {
    drupal_not_found();
    exit();
  }
}
